version: "3.9"

services:

  backend:
    platform: linux/amd64
    build: ./msme-backend
    ports:
      - "5000:5000"
    env_file:
      - msme-backend/.env
    restart: always

  frontend:
    platform: linux/amd64
    build:
      context: ./msme-frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always